#!/usr/bin/env python3
"""Build `Receipt Bridge.app` — a real macOS menu-bar application.

    python build_app.py              # build into dist/
    python build_app.py --install    # build and move into /Applications

The bundle launches the menu-bar app using this project's virtualenv rather
than embedding its own copy of Python. That is a deliberate choice: Playwright
keeps its Chromium in a shared cache outside any bundle, so a "self-contained"
build would still depend on something external — while being far more fragile.
This way there is one obvious place where the code lives, and the app is a
genuine double-clickable .app with no terminal in sight.

The trade-off: the bundle points at this folder. Move the project and rebuild.
"""

from __future__ import annotations

import argparse
import os
import plistlib
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
APP_NAME = "Receipt Bridge"
BUNDLE_ID = "com.receiptbridge.app"
EXECUTABLE = "ReceiptBridge"

LAUNCHER = """#!/bin/bash
# Launcher for {app_name}. Generated by build_app.py — edit that, not this.
PROJECT="{project}"
PYTHON="$PROJECT/.venv/bin/python"

if [ ! -x "$PYTHON" ]; then
  osascript -e 'display alert "{app_name} can’t start" message "The project folder has moved or its virtualenv is missing.\\n\\nExpected:\\n{project}\\n\\nRe-run build_app.py from wherever the project now lives." as critical'
  exit 1
fi

cd "$PROJECT" || exit 1
mkdir -p "$PROJECT/data"
# A bundle has nowhere to print, so keep a log worth reading when it misbehaves.
exec "$PYTHON" -m app.mac_app >> "$PROJECT/data/app.log" 2>&1
"""


NATIVE_LAUNCHER = r"""// Receipt Bridge launcher. Generated by build_app.py — edit that, not this.
//
// Embeds Python in this executable rather than handing off to Python's own
// app. With a shell-script launcher, macOS saw the running process as
// "Python": the Dock, Cmd-Tab and the app menu said Python, and because the
// system thought Receipt Bridge was not running, opening it again launched a
// second copy. Running Python in-process makes this bundle the real app.
#include <Python.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/stat.h>

#define PROJECT   "{project}"
#define VENV_PY   "{venv_python}"
#define LOG_FILE  "{log_file}"

static int fail(const char *what) {{
    char cmd[2048];
    snprintf(cmd, sizeof cmd,
        "osascript -e 'display alert \"Receipt Bridge can’t start\" "
        "message \"%s\\n\\nRe-run build_app.py from the project folder.\" as critical'",
        what);
    system(cmd);
    return 1;
}}

int main(int argc, char **argv) {{
    if (chdir(PROJECT) != 0) return fail("The project folder has moved.");
    if (access(VENV_PY, X_OK) != 0) return fail("The project's .venv is missing.");

    // A bundle has no terminal; keep output somewhere worth reading, and
    // stop it growing without bound: past 2 MB it is moved aside once.
    struct stat st;
    if (stat(LOG_FILE, &st) == 0 && st.st_size > 2 * 1024 * 1024) {{
        rename(LOG_FILE, LOG_FILE ".1");
    }}
    freopen(LOG_FILE, "a", stdout);
    freopen(LOG_FILE, "a", stderr);
    setvbuf(stdout, NULL, _IOLBF, 0);

    PyConfig config;
    PyConfig_InitPythonConfig(&config);
    PyStatus status;
    // Pointing `executable` at the venv's interpreter is what makes Python
    // find .venv/pyvenv.cfg and put the venv's packages on sys.path.
    status = PyConfig_SetBytesString(&config, &config.executable, VENV_PY);
    if (PyStatus_Exception(status)) goto error;
    status = PyConfig_SetBytesString(&config, &config.program_name, VENV_PY);
    if (PyStatus_Exception(status)) goto error;
    status = PyConfig_SetBytesString(&config, &config.run_module, "app.mac_app");
    if (PyStatus_Exception(status)) goto error;
    status = PyConfig_SetBytesArgv(&config, 1, argv);
    if (PyStatus_Exception(status)) goto error;

    status = Py_InitializeFromConfig(&config);
    if (PyStatus_Exception(status)) goto error;
    PyConfig_Clear(&config);
    return Py_RunMain();

error:
    PyConfig_Clear(&config);
    Py_ExitStatusException(status);
}}
"""


def compile_launcher(target: Path) -> bool:
    """Build the native launcher. False means fall back to the script."""
    import sysconfig

    venv_python = ROOT / ".venv" / "bin" / "python"
    config_tool = Path(sysconfig.get_config_var("BINDIR") or "") / (
        f"python{sysconfig.get_python_version()}-config"
    )
    if not config_tool.exists():
        print(f"  (no {config_tool.name}; using the script launcher)")
        return False

    flags = subprocess.run(
        [str(config_tool), "--cflags", "--embed", "--ldflags"],
        capture_output=True, text=True,
    ).stdout.split()
    source = target.with_suffix(".c")
    source.write_text(
        NATIVE_LAUNCHER.format(
            project=ROOT,
            venv_python=venv_python,
            log_file=ROOT / "data" / "app.log",
        ),
        encoding="utf-8",
    )
    result = subprocess.run(
        ["clang", "-O2", "-Wno-unused-result", str(source), "-o", str(target), *flags],
        capture_output=True, text=True,
    )
    source.unlink(missing_ok=True)
    if result.returncode != 0:
        print(f"  (launcher did not compile, using the script: {result.stderr.strip()[:300]})")
        return False
    print("  native launcher compiled")
    return True


ICON_HTML = """
<html><head><style>
  html,body{margin:0;padding:0;width:1024px;height:1024px;}
  body{display:flex;align-items:center;justify-content:center;
       background:linear-gradient(145deg,#1d4ed8,#0f2f8f);}
  .card{width:600px;height:720px;background:#fff;border-radius:48px;
        box-shadow:0 30px 80px rgba(0,0,0,.28);padding:70px 66px;
        box-sizing:border-box;font-family:-apple-system,Helvetica,Arial;}
  .bar{height:34px;border-radius:17px;background:#c9d3e4;margin-bottom:34px;}
  .bar.s{width:58%;} .bar.m{width:82%;} .bar.l{width:100%;}
  .rule{height:8px;background:#1f2933;border-radius:4px;margin:56px 0 40px;}
  .total{display:flex;justify-content:space-between;align-items:baseline;}
  .total span{font-size:74px;font-weight:800;color:#1f2933;}
</style></head><body><div class="card">
  <div class="bar l"></div><div class="bar m"></div><div class="bar s"></div>
  <div class="rule"></div>
  <div class="total"><span>£</span><span>✓</span></div>
</div></body></html>
"""


def build_icon(resources: Path) -> bool:
    """Render an app icon with the Chromium we already depend on."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return False

    iconset = resources.parent / "icon.iconset"
    png = resources.parent / "icon-1024.png"
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page(viewport={"width": 1024, "height": 1024})
            page.set_content(ICON_HTML)
            page.screenshot(path=str(png))
            browser.close()

        iconset.mkdir(parents=True, exist_ok=True)
        for size in (16, 32, 64, 128, 256, 512):
            for scale, suffix in ((1, ""), (2, "@2x")):
                out = iconset / f"icon_{size}x{size}{suffix}.png"
                subprocess.run(
                    ["sips", "-z", str(size * scale), str(size * scale),
                     str(png), "--out", str(out)],
                    check=True, capture_output=True,
                )
        subprocess.run(
            ["iconutil", "-c", "icns", str(iconset),
             "-o", str(resources / "icon.icns")],
            check=True, capture_output=True,
        )
        return True
    except Exception as exc:
        print(f"  (skipping icon: {exc})")
        return False
    finally:
        shutil.rmtree(iconset, ignore_errors=True)
        png.unlink(missing_ok=True)


def build(destination: Path) -> Path:
    bundle = destination / f"{APP_NAME}.app"
    if bundle.exists():
        shutil.rmtree(bundle)

    macos = bundle / "Contents" / "MacOS"
    resources = bundle / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    print(f"Building {bundle}")
    has_icon = build_icon(resources)

    # app/updates.py is the one place the version is written down. Read, not
    # imported, so building doesn't need the app's dependencies.
    found = re.search(r'^VERSION = "([^"]+)"', (ROOT / "app" / "updates.py").read_text(encoding="utf-8"), re.M)
    version = found.group(1) if found else "1.0.0"

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": version,
        "CFBundleShortVersionString": version,
        "CFBundleExecutable": EXECUTABLE,
        "CFBundlePackageType": "APPL",
        "NSHighResolutionCapable": True,
        # A regular app: Dock icon, menu bar, Cmd-Tab.
        "LSUIElement": False,
        "LSMinimumSystemVersion": "11.0",
    }
    if has_icon:
        info["CFBundleIconFile"] = "icon"

    with (bundle / "Contents" / "Info.plist").open("wb") as handle:
        plistlib.dump(info, handle)

    launcher = macos / EXECUTABLE
    (ROOT / "data").mkdir(exist_ok=True)
    if not compile_launcher(launcher):
        launcher.write_text(
            LAUNCHER.format(app_name=APP_NAME, project=ROOT), encoding="utf-8"
        )
        launcher.chmod(0o755)

    sign(bundle)
    return bundle


def sign(bundle: Path) -> None:
    """Ad-hoc sign the bundle so macOS treats it as a stable app identity.

    Without a signature, TCC silently returns "Operation not permitted" when
    the app touches a protected folder such as ~/Documents — no prompt, no
    error, just an app that appears to start and then does nothing. Signing
    makes macOS show the normal "would like to access" dialog instead.
    """
    result = subprocess.run(
        ["codesign", "--force", "--deep", "--sign", "-", str(bundle)],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        print("  signed (ad-hoc)")
    else:
        print(f"  (could not sign: {result.stderr.strip()})")


def main() -> int:
    parser = argparse.ArgumentParser(description=f"Build {APP_NAME}.app")
    parser.add_argument(
        "--install", action="store_true", help="move the bundle to /Applications"
    )
    args = parser.parse_args()

    if sys.platform != "darwin":
        print("This builder makes a macOS .app bundle.", file=sys.stderr)
        return 1

    if not (ROOT / ".venv" / "bin" / "python").exists():
        print("No .venv found — create it before building.", file=sys.stderr)
        return 1

    dist = ROOT / "dist"
    dist.mkdir(exist_ok=True)
    bundle = build(dist)

    if args.install:
        target = Path("/Applications") / bundle.name
        if target.exists():
            shutil.rmtree(target)
        shutil.move(str(bundle), str(target))
        bundle = target
        print(f"Installed to {bundle}")

    print(f"\nDone. Double-click {bundle}")
    print("It lives in the Dock; closing the window keeps it checking in the background.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
