"""Render a confirmation email into a receipt PDF.

The PDF is the original email, printed, with a summary band stapled to the top
carrying the fields the watcher extracted. That band is what makes the file
readable at a glance in FreeAgent — and it records where the document came
from, which matters when someone questions an expense two years later.
"""

from __future__ import annotations

import html as html_lib
import logging
import re
from pathlib import Path
from typing import Any

from .browser import BrowserPool

log = logging.getLogger(__name__)

# Strip anything that would make the printed page interactive or noisy.
_SCRIPTS = re.compile(r"(?is)<script\b.*?</script>")

SUMMARY_CSS = """
<style>
  @page { size: %(format)s; margin: %(margin)s; }
  body { margin: 0; }
  .rb-summary {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    border: 1.5px solid #1f2933;
    border-radius: 6px;
    padding: 14px 18px;
    margin: 0 0 22px 0;
    color: #1f2933;
    font-size: 12px;
    line-height: 1.5;
    page-break-inside: avoid;
  }
  .rb-summary h1 {
    font-size: 15px;
    margin: 0 0 10px 0;
    letter-spacing: 0.02em;
    text-transform: uppercase;
  }
  .rb-summary dl {
    display: grid;
    grid-template-columns: max-content 1fr;
    gap: 4px 18px;
    margin: 0;
  }
  .rb-summary dt { font-weight: 600; color: #52606d; }
  .rb-summary dd { margin: 0; }
  .rb-total { font-size: 15px; font-weight: 700; }
  .rb-note {
    margin-top: 10px;
    padding-top: 8px;
    border-top: 1px solid #cbd2d9;
    color: #616e7c;
    font-size: 10px;
  }
</style>
"""

SUMMARY_HTML = """
<div class="rb-summary">
  <h1>%(vendor)s receipt</h1>
  <dl>%(rows)s</dl>
  <div class="rb-note">%(note)s</div>
</div>
"""


def _row(label: str, value: Any) -> str:
    if value in (None, ""):
        return ""
    return (
        f"<dt>{html_lib.escape(label)}</dt>"
        f"<dd>{html_lib.escape(str(value))}</dd>"
    )


def build_summary(values: dict[str, Any], note: str) -> str:
    total = values.get("total")
    currency = values.get("currency") or ""
    amount = f"{currency} {total:.2f}" if isinstance(total, (int, float)) else total

    rows = "".join(
        [
            _row("Supplier", values.get("vendor")),
            _row("Date of payment", values.get("purchased_on")),
            _row("Reference", values.get("reference")),
            _row("Description", values.get("description")),
            _row("Paid by", values.get("card_type") or values.get("payment_type")),
        ]
    )
    if amount:
        rows += (
            "<dt>Total</dt>"
            f'<dd class="rb-total">{html_lib.escape(str(amount))}</dd>'
        )

    return SUMMARY_HTML % {
        "vendor": html_lib.escape(str(values.get("vendor", "Receipt"))),
        "rows": rows,
        "note": html_lib.escape(note),
    }


def render_email_to_pdf(
    pool: BrowserPool,
    email_html: str,
    values: dict[str, Any],
    out_path: Path,
    pdf_config: dict[str, Any] | None = None,
    note: str = "",
) -> Path:
    """Print the confirmation email to `out_path` and return the path."""
    settings = pdf_config or {}
    page_format = settings.get("format", "A4")
    margin = settings.get("margin", "12mm")

    body = _SCRIPTS.sub("", email_html)
    note = note or (
        "Generated by Receipt Bridge from the original confirmation email. "
        "The pages below are that email, unmodified."
    )
    document = (
        "<!doctype html><html><head><meta charset='utf-8'>"
        + SUMMARY_CSS % {"format": page_format, "margin": margin}
        + "</head><body>"
        + build_summary(values, note)
        + body
        + "</body></html>"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with pool.page() as page:
        page.set_content(document, wait_until="load")
        try:
            # Give remote logos a moment, but never hang on a dead tracker.
            page.wait_for_load_state("networkidle", timeout=8000)
        except Exception:
            log.debug("networkidle timed out while rendering; printing anyway")
        page.emulate_media(media="screen")
        page.pdf(
            path=str(out_path),
            format=page_format,
            print_background=True,
            margin={
                "top": margin,
                "bottom": margin,
                "left": margin,
                "right": margin,
            },
        )
    return out_path


def page_to_pdf(
    page: Any, out_path: Path, pdf_config: dict[str, Any] | None = None
) -> Path:
    """Print whatever a live page is currently showing."""
    settings = pdf_config or {}
    margin = settings.get("margin", "12mm")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    page.emulate_media(media="screen")
    page.pdf(
        path=str(out_path),
        format=settings.get("format", "A4"),
        print_background=True,
        margin={"top": margin, "bottom": margin, "left": margin, "right": margin},
    )
    return out_path
