"""Scan Gmail, turn matching emails into staged receipt PDFs.

Nothing here leaves the machine except the Gmail reads and whatever a fetcher
does on the vendor's own site. Staged receipts sit in the database until the
review screen exports them.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any, Callable

from . import fetchers
from .browser import BrowserPool, BrowserUnavailable
from .config import Config
from .db import FAILED, PENDING, Database
from .email_message import Email
from .fetchers.base import FetchContext
from .gmail_client import GmailClient, with_date_window
from .pdf import render_email_to_pdf
from .receipt_text import find_vat_number
from .watchers import Watcher, WatcherError, build_filename

log = logging.getLogger(__name__)

Progress = Callable[[str], None]


@dataclass
class ScanReport:
    scanned: int = 0
    staged: int = 0
    already_seen: int = 0
    not_matched: int = 0
    failed: int = 0
    notes: list[str] = field(default_factory=list)

    def note(self, message: str) -> None:
        self.notes.append(message)

    @property
    def summary(self) -> str:
        return (
            f"{self.scanned} email(s) checked, {self.staged} staged, "
            f"{self.already_seen} already known, {self.failed} failed"
        )


def _safe_stem(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]", "", value)[:80] or "receipt"


def resolve_pdf(
    config: Config,
    pool: BrowserPool | None,
    watcher: Watcher,
    message: Email,
    values: dict[str, Any],
    out_path: Path,
) -> tuple[Path, str, str]:
    """Work through the watcher's `pdf:` list until something produces a file.

    Returns (path, source, note). Raises RuntimeError if every step failed.
    """
    problems: list[str] = []

    for step in watcher.pdf:
        options: dict[str, Any] = {}
        if isinstance(step, dict):
            name = step.get("fetcher") or step.get("step") or ""
            options = {k: v for k, v in step.items() if k not in ("fetcher", "step")}
        else:
            name = str(step)

        if name == "attachment":
            # The supplier attached their own invoice. Nothing beats it: it is
            # the real document, already a PDF, needing neither a browser nor
            # a rendering step that could distort it.
            candidates = message.pdf_attachments(options.get("filename_matches"))
            if not candidates:
                problems.append("attachment: no matching PDF attachment")
                continue
            chosen = candidates[0]
            out_path.write_bytes(chosen["data"])
            return out_path, "email_attachment", chosen.get("filename", "")

        if name == "render_email":
            if pool is None:
                problems.append("render_email: no browser available")
                continue
            note = (
                "Generated by Receipt Bridge from the original confirmation "
                "email. The pages below are that email, unmodified."
            )
            render_email_to_pdf(
                pool,
                message.html or f"<pre>{message.plain}</pre>",
                values,
                out_path,
                config.pdf,
                note=note,
            )
            return out_path, "rendered_email", note

        if pool is None:
            problems.append(f"{name}: no browser available")
            continue

        if not config.fetchers_enabled:
            problems.append(f"{name}: fetchers disabled in config")
            continue

        fetcher = fetchers.get(name)
        if fetcher is None:
            problems.append(f"{name}: no such fetcher")
            continue

        context = FetchContext(
            pool=pool,
            message=message,
            values=values,
            options=options,
            out_path=out_path,
            debug_dir=config.debug_dir if config.debug_on_failure else Path(),
            timeout_seconds=config.fetch_timeout,
            pdf_config=config.pdf,
        )
        result = fetcher.fetch(context)
        if result is not None:
            return result.path, result.source, result.note
        problems.append(f"{name}: returned no document")

    raise RuntimeError("; ".join(problems) or "no pdf steps configured")


def process_email(
    config: Config,
    db: Database,
    watcher: Watcher,
    message: Email,
    pool: BrowserPool | None,
    report: ScanReport,
    account: str = "",
) -> int | None:
    """Extract, fetch a PDF for, and stage one email. Returns the row id."""
    if not watcher.matches(message):
        report.not_matched += 1
        return None

    if db.has_message(message.message_id):
        report.already_seen += 1
        return None

    flags: list[str] = []
    try:
        values = watcher.extract(message)
    except WatcherError as exc:
        # Like a photo: keep what was found, read the rest with the general
        # rules, and let a person fill in what's still missing (Files → To
        # check). Never set aside as "couldn't read".
        report.note(f"[{watcher.id}] {exc}: staged with what could be read")
        try:
            values = watcher.extract(message, strict=False)
        except Exception:
            values = {"vendor": watcher.vendor, "watcher": watcher.id, "subject": message.subject,
                      "email_date": message.date_iso, "purchased_on": message.date_iso}
        flags = fill_from_text(values, message)
    if values.get("vat") in (None, "") and not any(spec.name == "vat" for spec in watcher.fields):
        read_vat_from_text(values, message)

    filename = build_filename(watcher.filename, values)
    pdf_path = config.pdf_dir / f"{_safe_stem(message.message_id)}.pdf"

    pdf_error = ""
    try:
        pdf_path, pdf_source, _ = resolve_pdf(
            config, pool, watcher, message, values, pdf_path
        )
    except Exception as exc:
        pdf_error = str(exc)
        pdf_path, pdf_source = None, None
        if flags:
            # partly read already: show the email itself rather than give up
            try:
                pdf_path = _render_fallback(config, pool, message, values,
                                            config.pdf_dir / f"{_safe_stem(message.message_id)}.pdf")
                pdf_source = "rendered_email"
            except Exception:
                flags.append("No document: the email couldn't be printed. Open it in Gmail.")
    if pdf_path is None and not flags:
        report.failed += 1
        report.note(f"[{watcher.id}] no PDF for {values.get('reference')}: {pdf_error}")
        db.insert_receipt(
            {
                "watcher_id": watcher.id,
                "gmail_message_id": message.message_id,
                "gmail_thread_id": message.thread_id,
                "vendor": values.get("vendor"),
                "reference": values.get("reference"),
                "purchased_on": values.get("purchased_on"),
                "total": values.get("total"),
                "currency": values.get("currency"),
                "description": values.get("description"),
                "subject": message.subject,
                "email_date": message.date_iso,
                "filename": filename,
                "status": FAILED,
                "error": pdf_error,
                "extra_json": {k: v for k, v in values.items() if k not in ("html",)},
            }
        )
        return None
    if flags:
        values["flags"] = flags

    reference = values.get("reference")
    if reference and db.has_reference(watcher.id, str(reference)):
        report.already_seen += 1
        report.note(f"[{watcher.id}] {reference} already staged, skipping")
        return None

    # the rule says who pays this supplier (Settings → Email receipts)
    paid_by = "personal" if watcher.paid_with == "personal" else None
    if watcher.paid_with.startswith("https://"):
        paid_by = "business"
        values["bank_account"] = watcher.paid_with
    receipt_id = db.insert_receipt(
        {
            "watcher_id": watcher.id,
            "paid_by": paid_by,
            "account": account,
            "gmail_message_id": message.message_id,
            "gmail_thread_id": message.thread_id,
            "vendor": values.get("vendor"),
            "reference": values.get("reference"),
            "purchased_on": values.get("purchased_on"),
            "total": values.get("total"),
            "currency": values.get("currency"),
            # The VAT the rule read, and the supplier's VAT number printed
            # beside it: what review checks before a VAT reclaim is filed.
            "vat": values.get("vat"),
            "vat_number": find_vat_number(f"{message.text}\n{message.attachment_text}",
                                          values.get("currency")),
            "description": values.get("description"),
            "subject": message.subject,
            "email_date": message.date_iso,
            "pdf_path": str(pdf_path) if pdf_path else None,
            "pdf_source": pdf_source,
            "filename": filename,
            "status": PENDING,
            "extra_json": {k: v for k, v in values.items()},
        }
    )
    if not receipt_id:
        # Another scan staged this one while we were fetching its PDF.
        report.already_seen += 1
        return None

    report.staged += 1
    report.note(f"[{watcher.id}] staged {filename} ({pdf_source})")
    return receipt_id


def fill_from_text(values: dict[str, Any], message: Email) -> list[str]:
    """A supplier rule that couldn't find everything: fill the gaps from the
    email's text with the general rules used for photos (app/receipt_text.py),
    and say what a person should check. Returns the flags."""
    from .receipt_text import read_rows
    from .supplier_builder import _amounts

    raw = f"{message.text}\n{message.attachment_text}"
    lines = [line for line in raw.splitlines() if line.strip()]
    text = read_rows(lines)
    missing = values.get("_missing") or []
    # The amount labelled as the total, with its own currency mark ("Total
    # US$71.08"): an email can mention £ or VAT elsewhere (a footer, the
    # company's address) while the trip was charged in dollars.
    labelled = sorted((c for c in _amounts(raw) if c.score > 0), key=lambda c: -c.score)
    best = labelled[0] if labelled else None
    values.pop("_missing", None)
    flags: list[str] = []
    found_currency = None
    if values.get("total") in (None, ""):
        if best is not None:
            values["total"] = float(best.value.replace(",", ""))
            found_currency = best.currency or None
        elif text.total is not None:
            values["total"] = float(text.total)
            # the currency printed with that very amount ("US$71.08"), else the email's
            same = [c.currency for c in _amounts(raw)
                    if c.currency and round(float(c.value.replace(",", "")), 2) == round(float(text.total), 2)]
            found_currency = same[0] if same else text.currency
        if values.get("total") is not None:
            flags.append("Total not confirmed: read from the email by the general rules. Check it.")
        else:
            flags.append("Total couldn't be read from the email. Type it in.")
    if "vat" in missing:
        # Never guessed: filing at 0% would quietly lose the reclaim.
        flags.append("VAT not found: the supplier's rule reads VAT, but not from this email. Check it.")
    if found_currency and values.get("currency") != found_currency:
        # the rule's fixed currency went with the total it couldn't find: the
        # currency printed beside the total wins (an Uber trip abroad)
        values["currency"] = found_currency
    elif not values.get("currency"):
        if found_currency or text.currency:
            values["currency"] = found_currency or text.currency
        else:
            flags.append("No currency shown. Which currency?")
    if not values.get("purchased_on"):
        values["purchased_on"] = text.date.isoformat() if text.date else message.date_iso
    return flags


def read_vat_from_text(values: dict[str, Any], message: Email) -> None:
    """A supplier rule with no VAT field: read the VAT printed on the invoice
    with the general rules, as for a photo. Without it, a VAT invoice was
    filed at 0% and its reclaim lost (Example Accountants)."""
    if values.get("currency") != "GBP" or values.get("total") in (None, ""):
        return
    from .receipt_text import find_vat_lines

    lines = [line for line in message.attachment_text.splitlines() if line.strip()] \
        or [line for line in message.text.splitlines() if line.strip()]
    vat, vat_lines = find_vat_lines(lines, "GBP", Decimal(str(values["total"])))
    if vat:
        values["vat"] = float(vat)
        values["vat_lines"] = [[None if r is None else str(r), str(v), None if g is None else str(g)]
                               for r, v, g in vat_lines]


def _render_fallback(config: Config, pool: BrowserPool | None, message: Email,
                     values: dict[str, Any], out_path: Path) -> Path:
    """The email itself, printed: the document for a partly read receipt."""
    if pool is None:
        raise RuntimeError("no browser available")
    return render_email_to_pdf(pool, message.html or f"<pre>{message.plain}</pre>", values, out_path, config.pdf,
                               note="Generated by Receipt Bridge from the original email. The pages below are "
                                    "that email, unmodified.")


def _acquire_scan_lock(config: Config) -> Any | None:
    """Take an exclusive lock, or return None if a scan is already running.

    The menu-bar app scans on launch and every six hours, so it is entirely
    normal for an automatic scan to be underway when someone starts one by
    hand. Without this they both walk the whole mailbox, doubling the browser
    work and racing each other into the database.

    The lock is an open file handle held for the duration; the OS drops it if
    the process dies, so a crashed scan cannot wedge every later one.
    """
    import fcntl

    config.data_dir.mkdir(parents=True, exist_ok=True)
    handle = (config.data_dir / "scan.lock").open("w")
    try:
        fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        handle.close()
        return None
    return handle


def _release_scan_lock(handle: Any) -> None:
    import fcntl

    try:
        fcntl.flock(handle, fcntl.LOCK_UN)
    finally:
        handle.close()


def scan(
    config: Config,
    db: Database,
    watchers: list[Watcher],
    gmail: GmailClient | None = None,
    progress: Progress | None = None,
    accounts: list[tuple[str, GmailClient]] | None = None,
    on_event: Callable[[dict[str, Any]], None] | None = None,
) -> ScanReport:
    """Run every enabled watcher against every connected mailbox.

    Pass `accounts` as (address, client) pairs to scan several, or a single
    `gmail` client for the one-mailbox case. One lock and one browser cover
    the whole run rather than being taken per account.
    """
    report = ScanReport()
    config.ensure_dirs()

    mailboxes: list[tuple[str, GmailClient]] = list(accounts or [])
    if not mailboxes and gmail is not None:
        mailboxes = [("", gmail)]

    def say(text: str) -> None:
        # Exactly one destination. Emitting to both a progress callback and
        # the log printed every line twice when the caller's progress function
        # was `print` and logging also went to stdout, which reads as though
        # each watcher ran twice — it cost real time during debugging.
        report.note(text)
        (progress or log.info)(text)

    def emit(kind: str, **data: Any) -> None:
        """Structured progress for the UI. Never allowed to break a scan."""
        if on_event is None:
            return
        try:
            on_event({"type": kind, **data})
        except Exception:
            log.debug("progress listener failed", exc_info=True)

    if not watchers:
        say("No enabled watchers found.")
        return report

    lock = _acquire_scan_lock(config)
    if lock is None:
        say("Another scan is already running — skipping this one.")
        return report

    pool: BrowserPool | None = None
    try:
        pool = BrowserPool(
            headless=config.headless,
            block_trackers=bool(config.pdf.get("block_trackers", True)),
        )

        for account_email, client in mailboxes:
            # Only label lines when there is more than one mailbox to tell
            # apart; a single-account scan reads better without the noise.
            label = f"{account_email} " if len(mailboxes) > 1 else ""

            for watcher in watchers:
                state_key = (
                    f"last_scan:{account_email}:{watcher.id}"
                    if account_email
                    else f"last_scan:{watcher.id}"
                )
                since = _parse_iso(db.get_state(state_key))
                query = with_date_window(
                    watcher.gmail_query,
                    since,
                    watcher.lookback_days or config.initial_lookback_days,
                    # how far back you chose when connecting this account
                    _parse_iso(db.get_state(f"scan_from:{account_email}")) if account_email else None,
                )
                say(f"[{label}{watcher.id}] searching: {query}")

                try:
                    stubs = client.search(
                        query, max_results=config.max_results_per_scan
                    )
                except Exception as exc:
                    report.failed += 1
                    say(f"[{label}{watcher.id}] Gmail search failed: {exc}")
                    continue

                say(f"[{label}{watcher.id}] {len(stubs)} candidate email(s)")
                emit(
                    "supplier",
                    supplier=watcher.name,
                    account=account_email,
                    total=len(stubs),
                )

                total = len(stubs)
                for position, stub in enumerate(stubs, start=1):
                    report.scanned += 1
                    if db.has_message(stub["id"]):
                        report.already_seen += 1
                        continue
                    try:
                        message = client.fetch(stub["id"], stub.get("threadId", ""))
                    except Exception as exc:
                        report.failed += 1
                        say(
                            f"[{label}{watcher.id}] could not read message "
                            f"{stub['id']}: {exc}"
                        )
                        continue

                    # Fetching a supplier's own receipt drives a headless
                    # browser and takes ten seconds or more per email. Without
                    # a line before the work starts, the screen sits silent
                    # for minutes and a running scan looks like a broken one.
                    say(
                        f"[{label}{watcher.id}] {position}/{total} "
                        f"{message.subject[:60]}"
                    )
                    emit(
                        "item",
                        supplier=watcher.name,
                        position=position,
                        total=total,
                        subject=message.subject,
                    )
                    staged_id = process_email(
                        config, db, watcher, message, pool, report, account_email
                    )
                    if staged_id:
                        emit("staged", supplier=watcher.name, receipt_id=staged_id)

                db.set_state(state_key, date.today().isoformat())

            if account_email:
                db.set_state(
                    f"last_scan_at:{account_email}", datetime.now().isoformat()
                )

    except BrowserUnavailable as exc:
        say(f"Browser unavailable: {exc}")
        report.failed += 1
    finally:
        if pool is not None:
            pool.close()
        _release_scan_lock(lock)

    say(report.summary)
    return report


def _parse_iso(value: str | None) -> date | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value).date()
    except ValueError:
        return None
